#!/bin/dash

#check if repo exist
if ! [ -d ".shrug" ]
then
    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
    exit 1
fi
#check number of arguments not 0
if [ "$#" -eq 0 ]
then
    echo "usage: shrug-add <filenames>"
    exit 1
fi
#check actually exist
for file in "$@"
do
    if ! [ -f "$file" ]
    then
        #if index has the file but current directory does not, then just exit
        #if index and current direcory both dont have the file, give error.
        cd .shrug/index
        if ! [ -f "$file" ]
        then
            echo "shrug-add: error: can not open '$file' "
            exit 1
        else
            exit 0
        fi
    fi
    #copy to index
    cp "$file" ".shrug/index"


done
