#!/bin/dash

if [ -d ".shrug" ]
then
  echo "shrug-init: error: .shrug already exists"
  exit 1
fi

mkdir .shrug
cd .shrug
mkdir index
mkdir commits
touch message
chmod 755 message


echo "Initialized empty shrug repository in .shrug"